# Cross-language parity tests for Phase 3 writers (fixed-width DSSAT editing).
# Byte-for-byte comparison against golden after-files generated by Python.

fixture_dir <- file.path("..", "fixtures")
if (!dir.exists(fixture_dir)) fixture_dir <- file.path("tests", "fixtures")
read_fix <- function(name) jsonlite::fromJSON(file.path(fixture_dir, name),
                                              simplifyVector = FALSE)
meta <- read_fix("writers_meta.json")

# copy a fixture into a temp file so the in-place editors don't touch goldens
tmp_copy <- function(name) {
  dst <- tempfile(fileext = paste0("_", name))
  file.copy(file.path(fixture_dir, name), dst, overwrite = TRUE)
  dst
}

test_that("_fmt matches Python at every width/precision", {
  for (k in names(meta$fmt_cases)) {
    parts <- strsplit(k, "_", fixed = TRUE)[[1]]
    v <- as.numeric(parts[1]); w <- as.integer(parts[2])
    expect_equal(.fmt(v, w), meta$fmt_cases[[k]], info = k)
  }
})

test_that("cultivar_field_map and parse_header_boundaries match Python", {
  fmap <- cultivar_field_map(file.path(fixture_dir, "sample.CUL"))
  for (k in names(meta$cultivar_field_map)) {
    expect_equal(unname(fmap[[k]]), as.numeric(unlist(meta$cultivar_field_map[[k]])), info = k)
  }
  hdr <- "@P    PDATE EDATE  PPOP  PPOE  PLME  PLDS  PLRS  PLRD  PLDP"
  ph <- parse_header_boundaries(hdr)
  for (k in names(meta$parse_header_boundaries)) {
    expect_equal(unname(ph[[k]]), as.numeric(unlist(meta$parse_header_boundaries[[k]])), info = k)
  }
})

test_that("edit_cultivar reproduces the Python after-file byte-for-byte", {
  f <- tmp_copy("sample.CUL")
  updates <- meta$cul_updates
  edit_cultivar(f, "IB0008", updates)
  got <- readLines(f, warn = FALSE)
  exp <- readLines(file.path(fixture_dir, "sample_cul_after.CUL"), warn = FALSE)
  expect_identical(got, exp)
})

test_that("edit_ecotype reproduces the Python after-file byte-for-byte", {
  f <- tmp_copy("sample.ECO")
  edit_ecotype(f, "SB0301", meta$eco_updates)
  got <- readLines(f, warn = FALSE)
  exp <- readLines(file.path(fixture_dir, "sample_eco_after.ECO"), warn = FALSE)
  expect_identical(got, exp)
})

test_that("edit_species preserves leading-dot decimals", {
  f <- tempfile(fileext = ".SPE")
  writeLines(c(
    " .0046 .0004 .3000  4.90 1.030             SLWREF,SLWSLO,NSLOPE,LNREF,PGREF",
    "! .0036 .0004 .3000  4.90 1.030             SLWREF,SLWSLO,NSLOPE,LNREF,PGREF"
  ), f)
  edit_species(f, list("SLWREF,SLWSLO,NSLOPE,LNREF,PGREF" = 0.0048))
  got <- readLines(f, warn = FALSE)
  expect_true(startsWith(got[1], " .0048 .0004"))
  expect_true(startsWith(got[2], "! .0036 .0004"))
})

test_that("edit_species can target a numeric token index", {
  f <- tempfile(fileext = ".SPE")
  writeLines("  40.00 61.00  0.96  0.10                   PARMAX,PHTMAX,KCAN,KC_SLOPE", f)
  edit_species(f, list("PARMAX,PHTMAX,KCAN,KC_SLOPE" = list(value = 0.88, index = 2L)))
  got <- readLines(f, warn = FALSE)
  expect_true(startsWith(got[1], "  40.00 61.00  0.88  0.10"))
})

test_that("read_cultivar_values and read_cul_calibration_bounds match Python", {
  vals <- read_cultivar_values(file.path(fixture_dir, "sample.CUL"), "IB0008")
  for (k in names(meta$read_cultivar_values)) {
    expect_equal(vals[[k]], as.numeric(meta$read_cultivar_values[[k]]), tolerance = 1e-9, info = k)
  }
  bounds <- read_cul_calibration_bounds(file.path(fixture_dir, "sample.CUL"))
  for (k in names(meta$calibration_bounds)) {
    expect_equal(bounds[[k]]$min, as.numeric(meta$calibration_bounds[[k]]$min), tolerance = 1e-9, info = k)
    expect_equal(bounds[[k]]$max, as.numeric(meta$calibration_bounds[[k]]$max), tolerance = 1e-9, info = k)
  }
})
